services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.prod
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      vectordb:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - corpus_data:/app/corpus
      - ./backend/config/app.production.yaml:/app/config/app.production.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/ >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  vectordb:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/6333' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

volumes:
  qdrant_data:
  corpus_data:
